services:
  postgres:
    image: postgres:15-alpine
    container_name: webrise_postgres
    environment:
      POSTGRES_DB: web_rise_demo
      POSTGRES_USER: web_rise_user
      POSTGRES_PASSWORD: "1"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U web_rise_user -d web_rise_demo"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webrise_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/web_rise_demo
      SPRING_DATASOURCE_USERNAME: web_rise_user
      SPRING_DATASOURCE_PASSWORD: "1"
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data: